CREATE DATABASE BDCADASTRO;

USE BDCADASTRO;

CREATE TABLE CLIENTE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(50) NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	UF CHAR(2) NOT NULL,
	TELEFONE VARCHAR(15)
);


SELECT * FROM CLIENTE;